#! /bin/bash
# create a pizaid-disk

usage_exit() {
	echo "Usage: pizaid-disk [-S sync] [-h help] PhysicalDevicePath" 1>&2
    exit 1
}

. $(dirname $0)/pizaid-common.sh

NAME="Pizaid"
OPT=`getopt -o :Sh -l sync,help -- "$@"`
if [ $? != 0 ] ; then
    usage_exit
fi
eval set -- "$OPT"
while [ $# -gt 0 ]; do
    case $1 in
        -s | --sync) NAME="Pizaid-Sync";;
        -h | --help) usage_exit ;;
        --) shift; break ;;
    esac
    shift
done

if [ $# != 1 ] ; then
    usage_exit
fi

DPATH=$1 #DevicePath
PizaidCheckHostName
PizaidCheckUser

PizaidCheckDevicePATH

if [ ! -e /dev/${NAME}-VG ]; then
    # create pizaid volume
    PizaidCreatePartition
    PizaidCreatePV
    PizaidCreateVG
    PizaidCreateLV
    PizaidMKFS
    # crate directory and mout
    mkdir -p /mnt/${NAME}
    mount /dev/${NAME}-VG/${NAME}-LV /mnt/${NAME}
    chown share:share /mnt/${NAME}
else
    # extend pizaid volume
    PizaidCreatePartition
    PizaidCreatePV
    PizaidExtendVG
    PizaidExtendLV
    PizaidReSizeFS
fi

service samba restart
