#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'controller_types'

module Pizaid
  module ControllerService
    class Client
      include ::Thrift::Client

      def network_ipv4()
        send_network_ipv4()
        return recv_network_ipv4()
      end

      def send_network_ipv4()
        send_message('network_ipv4', Network_ipv4_args)
      end

      def recv_network_ipv4()
        result = receive_message(Network_ipv4_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'network_ipv4 failed: unknown result')
      end

      def network_ipv6()
        send_network_ipv6()
        return recv_network_ipv6()
      end

      def send_network_ipv6()
        send_message('network_ipv6', Network_ipv6_args)
      end

      def recv_network_ipv6()
        result = receive_message(Network_ipv6_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'network_ipv6 failed: unknown result')
      end

      def storage_storage_group_list()
        send_storage_storage_group_list()
        return recv_storage_storage_group_list()
      end

      def send_storage_storage_group_list()
        send_message('storage_storage_group_list', Storage_storage_group_list_args)
      end

      def recv_storage_storage_group_list()
        result = receive_message(Storage_storage_group_list_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_storage_group_list failed: unknown result')
      end

      def storage_capacity_kb(key)
        send_storage_capacity_kb(key)
        return recv_storage_capacity_kb()
      end

      def send_storage_capacity_kb(key)
        send_message('storage_capacity_kb', Storage_capacity_kb_args, :key => key)
      end

      def recv_storage_capacity_kb()
        result = receive_message(Storage_capacity_kb_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_capacity_kb failed: unknown result')
      end

      def storage_usage_kb(key)
        send_storage_usage_kb(key)
        return recv_storage_usage_kb()
      end

      def send_storage_usage_kb(key)
        send_message('storage_usage_kb', Storage_usage_kb_args, :key => key)
      end

      def recv_storage_usage_kb()
        result = receive_message(Storage_usage_kb_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_usage_kb failed: unknown result')
      end

      def storage_usage_percent(key)
        send_storage_usage_percent(key)
        return recv_storage_usage_percent()
      end

      def send_storage_usage_percent(key)
        send_message('storage_usage_percent', Storage_usage_percent_args, :key => key)
      end

      def recv_storage_usage_percent()
        result = receive_message(Storage_usage_percent_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_usage_percent failed: unknown result')
      end

      def storage_is_sync()
        send_storage_is_sync()
        return recv_storage_is_sync()
      end

      def send_storage_is_sync()
        send_message('storage_is_sync', Storage_is_sync_args)
      end

      def recv_storage_is_sync()
        result = receive_message(Storage_is_sync_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_is_sync failed: unknown result')
      end

      def storage_join(key, disk)
        send_storage_join(key, disk)
        return recv_storage_join()
      end

      def send_storage_join(key, disk)
        send_message('storage_join', Storage_join_args, :key => key, :disk => disk)
      end

      def recv_storage_join()
        result = receive_message(Storage_join_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_join failed: unknown result')
      end

      def storage_disk_list(key)
        send_storage_disk_list(key)
        return recv_storage_disk_list()
      end

      def send_storage_disk_list(key)
        send_message('storage_disk_list', Storage_disk_list_args, :key => key)
      end

      def recv_storage_disk_list()
        result = receive_message(Storage_disk_list_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_disk_list failed: unknown result')
      end

      def storage_disk_id(disk)
        send_storage_disk_id(disk)
        return recv_storage_disk_id()
      end

      def send_storage_disk_id(disk)
        send_message('storage_disk_id', Storage_disk_id_args, :disk => disk)
      end

      def recv_storage_disk_id()
        result = receive_message(Storage_disk_id_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_disk_id failed: unknown result')
      end

      def storage_disk_size(disk)
        send_storage_disk_size(disk)
        return recv_storage_disk_size()
      end

      def send_storage_disk_size(disk)
        send_message('storage_disk_size', Storage_disk_size_args, :disk => disk)
      end

      def recv_storage_disk_size()
        result = receive_message(Storage_disk_size_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_disk_size failed: unknown result')
      end

      def storage_disk_port(disk)
        send_storage_disk_port(disk)
        return recv_storage_disk_port()
      end

      def send_storage_disk_port(disk)
        send_message('storage_disk_port', Storage_disk_port_args, :disk => disk)
      end

      def recv_storage_disk_port()
        result = receive_message(Storage_disk_port_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'storage_disk_port failed: unknown result')
      end

      def power_battery_percent()
        send_power_battery_percent()
        return recv_power_battery_percent()
      end

      def send_power_battery_percent()
        send_message('power_battery_percent', Power_battery_percent_args)
      end

      def recv_power_battery_percent()
        result = receive_message(Power_battery_percent_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'power_battery_percent failed: unknown result')
      end

      def power_is_ac_plugin()
        send_power_is_ac_plugin()
        return recv_power_is_ac_plugin()
      end

      def send_power_is_ac_plugin()
        send_message('power_is_ac_plugin', Power_is_ac_plugin_args)
      end

      def recv_power_is_ac_plugin()
        result = receive_message(Power_is_ac_plugin_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'power_is_ac_plugin failed: unknown result')
      end

    end

    class Processor
      include ::Thrift::Processor

      def process_network_ipv4(seqid, iprot, oprot)
        args = read_args(iprot, Network_ipv4_args)
        result = Network_ipv4_result.new()
        result.success = @handler.network_ipv4()
        write_result(result, oprot, 'network_ipv4', seqid)
      end

      def process_network_ipv6(seqid, iprot, oprot)
        args = read_args(iprot, Network_ipv6_args)
        result = Network_ipv6_result.new()
        result.success = @handler.network_ipv6()
        write_result(result, oprot, 'network_ipv6', seqid)
      end

      def process_storage_storage_group_list(seqid, iprot, oprot)
        args = read_args(iprot, Storage_storage_group_list_args)
        result = Storage_storage_group_list_result.new()
        result.success = @handler.storage_storage_group_list()
        write_result(result, oprot, 'storage_storage_group_list', seqid)
      end

      def process_storage_capacity_kb(seqid, iprot, oprot)
        args = read_args(iprot, Storage_capacity_kb_args)
        result = Storage_capacity_kb_result.new()
        result.success = @handler.storage_capacity_kb(args.key)
        write_result(result, oprot, 'storage_capacity_kb', seqid)
      end

      def process_storage_usage_kb(seqid, iprot, oprot)
        args = read_args(iprot, Storage_usage_kb_args)
        result = Storage_usage_kb_result.new()
        result.success = @handler.storage_usage_kb(args.key)
        write_result(result, oprot, 'storage_usage_kb', seqid)
      end

      def process_storage_usage_percent(seqid, iprot, oprot)
        args = read_args(iprot, Storage_usage_percent_args)
        result = Storage_usage_percent_result.new()
        result.success = @handler.storage_usage_percent(args.key)
        write_result(result, oprot, 'storage_usage_percent', seqid)
      end

      def process_storage_is_sync(seqid, iprot, oprot)
        args = read_args(iprot, Storage_is_sync_args)
        result = Storage_is_sync_result.new()
        result.success = @handler.storage_is_sync()
        write_result(result, oprot, 'storage_is_sync', seqid)
      end

      def process_storage_join(seqid, iprot, oprot)
        args = read_args(iprot, Storage_join_args)
        result = Storage_join_result.new()
        result.success = @handler.storage_join(args.key, args.disk)
        write_result(result, oprot, 'storage_join', seqid)
      end

      def process_storage_disk_list(seqid, iprot, oprot)
        args = read_args(iprot, Storage_disk_list_args)
        result = Storage_disk_list_result.new()
        result.success = @handler.storage_disk_list(args.key)
        write_result(result, oprot, 'storage_disk_list', seqid)
      end

      def process_storage_disk_id(seqid, iprot, oprot)
        args = read_args(iprot, Storage_disk_id_args)
        result = Storage_disk_id_result.new()
        result.success = @handler.storage_disk_id(args.disk)
        write_result(result, oprot, 'storage_disk_id', seqid)
      end

      def process_storage_disk_size(seqid, iprot, oprot)
        args = read_args(iprot, Storage_disk_size_args)
        result = Storage_disk_size_result.new()
        result.success = @handler.storage_disk_size(args.disk)
        write_result(result, oprot, 'storage_disk_size', seqid)
      end

      def process_storage_disk_port(seqid, iprot, oprot)
        args = read_args(iprot, Storage_disk_port_args)
        result = Storage_disk_port_result.new()
        result.success = @handler.storage_disk_port(args.disk)
        write_result(result, oprot, 'storage_disk_port', seqid)
      end

      def process_power_battery_percent(seqid, iprot, oprot)
        args = read_args(iprot, Power_battery_percent_args)
        result = Power_battery_percent_result.new()
        result.success = @handler.power_battery_percent()
        write_result(result, oprot, 'power_battery_percent', seqid)
      end

      def process_power_is_ac_plugin(seqid, iprot, oprot)
        args = read_args(iprot, Power_is_ac_plugin_args)
        result = Power_is_ac_plugin_result.new()
        result.success = @handler.power_is_ac_plugin()
        write_result(result, oprot, 'power_is_ac_plugin', seqid)
      end

    end

    # HELPER FUNCTIONS AND STRUCTURES

    class Network_ipv4_args
      include ::Thrift::Struct, ::Thrift::Struct_Union

      FIELDS = {

      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Network_ipv4_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Network_ipv6_args
      include ::Thrift::Struct, ::Thrift::Struct_Union

      FIELDS = {

      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Network_ipv6_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_storage_group_list_args
      include ::Thrift::Struct, ::Thrift::Struct_Union

      FIELDS = {

      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_storage_group_list_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRING}}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_capacity_kb_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      KEY = 1

      FIELDS = {
        KEY => {:type => ::Thrift::Types::STRING, :name => 'key'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_capacity_kb_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::I64, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_usage_kb_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      KEY = 1

      FIELDS = {
        KEY => {:type => ::Thrift::Types::STRING, :name => 'key'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_usage_kb_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::I64, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_usage_percent_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      KEY = 1

      FIELDS = {
        KEY => {:type => ::Thrift::Types::STRING, :name => 'key'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_usage_percent_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::BYTE, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_is_sync_args
      include ::Thrift::Struct, ::Thrift::Struct_Union

      FIELDS = {

      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_is_sync_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_join_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      KEY = 1
      DISK = 2

      FIELDS = {
        KEY => {:type => ::Thrift::Types::STRING, :name => 'key'},
        DISK => {:type => ::Thrift::Types::STRING, :name => 'disk'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_join_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_disk_list_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      KEY = 1

      FIELDS = {
        KEY => {:type => ::Thrift::Types::STRING, :name => 'key'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_disk_list_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRING}}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_disk_id_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      DISK = 1

      FIELDS = {
        DISK => {:type => ::Thrift::Types::STRING, :name => 'disk'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_disk_id_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_disk_size_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      DISK = 1

      FIELDS = {
        DISK => {:type => ::Thrift::Types::STRING, :name => 'disk'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_disk_size_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_disk_port_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      DISK = 1

      FIELDS = {
        DISK => {:type => ::Thrift::Types::STRING, :name => 'disk'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Storage_disk_port_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::BYTE, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Power_battery_percent_args
      include ::Thrift::Struct, ::Thrift::Struct_Union

      FIELDS = {

      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Power_battery_percent_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::BYTE, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Power_is_ac_plugin_args
      include ::Thrift::Struct, ::Thrift::Struct_Union

      FIELDS = {

      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Power_is_ac_plugin_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end

end
